# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f7219812b9b0849e1d8881e72f0249071f1352074ab44b9d75e9bc720e3f877475433f829a3f97dc06e4491268360b7d1029c66c16c69460a8834af37a664bd

test:
  secret_key_base: a99d3de2a91bc59d94553f8bcd482091a1106540c990940944fb57255799f2e8ee2b26bec81cc8df6c6007330426d37ad424947a42961ad5ccfcf168785867df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
